### PR TITLE
Added git info support. Beware of my implementation

### PR DESCRIPTION
**Pull request by RyanCopley**
This is just to give you an idea. It's a really crappy implementation, but your current version does not have git info support. This is how you do it, you might want to find a better way.

### CODE REVIEW

**Comment by RyanCopley** [comment]
That awkward moment when I didn't write any unit tests...

**Comment by macmade** [comment]
lol, thanks for the request, and no worries for the unit-tests ; )
I'll review the pull-request and let you know about it...

Cheers,

**Comment by RyanCopley** [comment]
screen shot 2015-02-26 at 10 06 24 pm

As a reference as to what I'm talking about

**Comment by RyanCopley** [comment]
I just went and looked at how https://github.com/coagulant/coveralls-python/blob/master/coveralls/api.py is implementing it, and I followed their process a bit more close. This should be a little bit less of a bad example now. You might want to move this to a different file in the project and/or add a --git flag

**Comment by macmade** [comment]
Ok, I've merged your pull request, as this is obviously a nice addition. Thanks.

I'll now try to see if I can manage to have a better implementation, possibly through libgit.  
Anyway, I think I'll put all this git stuff into a separate class, rather than directly into the request class.

**Comment by macmade** [comment]
FYI, libgit is the way to go.

I've done a simple test, and it's very easy to get all the infos required by coveralls.  
So I'm now going to refactor your code, so it uses libgit instead of NSTask.

I've created a gist, so you can see an example: https://gist.github.com/macmade/dd676aad77651ccda958

Cheers : )

**Comment by RyanCopley** [comment]
Very cool, I didn't know libgit was a thing. Thanks for this project by the way, it's miles better than the default coveralls iOS setup

**Comment by macmade** [comment]
Ok, I've replaced your implementation with a libgit one.
Everything should work as expected. Please tell me if you have issues.

**Pull request merged**
